In [8]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, classification_report
import matplotlib.pyplot as plt
from sklearn import tree
import seaborn as sns
plt.rcParams['figure.figsize'] = (10,5)
plt.rcParams['figure.dpi'] = 1000
sns.set_theme(style='darkgrid', palette='rainbow')
import warnings
warnings.filterwarnings('ignore')

In [1]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [2]:
df=sns.load_dataset("iris")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


# EDA 

In [9]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [66]:
x = df.iloc[:,:-1]
y = df['species']

In [67]:
from sklearn.preprocessing import StandardScaler 

In [68]:
scaler= StandardScaler()
scale_df=scaler.fit_transform(x)
x=pd.DataFrame(scale_df,columns=x.columns)

In [69]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [70]:
xtest

sepal_length  sepal_width  petal_length  petal_width
14      -0.052506     2.169988     -1.453901    -1.315444
98      -0.900681    -1.282963     -0.430828    -0.130755
75       0.916837    -0.131979      0.364896     0.264142
16      -0.537178     1.939791     -1.397064    -1.052180
131      2.492019     1.709595      1.501645     1.053935
56       0.553333     0.558611      0.535409     0.527406
141      1.280340     0.098217      0.762758     1.448832
44      -0.900681     1.709595     -1.056039    -1.052180
29      -1.385353     0.328414     -1.226552    -1.315444
120      1.280340     0.328414      1.103783     1.448832
94      -0.294842    -0.822570      0.251221     0.132510
5       -0.537178     1.939791     -1.169714    -1.052180
102      1.522676    -0.131979      1.217458     1.185567
51       0.674501     0.328414      0.421734     0.395774
78       0.189830    -0.362176      0.421734     0.395774
42      -1.748856     0.328414     -1.397064    -1.315444
92      -0.052506    -1.052767      0.137547     0.000878
66      -0.294842    -0.131979      0.421734     0.395774
31      -0.537178     0.788808     -1.283389    -1.052180
35      -1.021849     0.328414     -1.453901    -1.315444
90      -0.416010    -1.052767      0.364896     0.000878
84      -0.537178    -0.131979      0.421734     0.395774
77       1.038005    -0.131979      0.705921     0.659038
40      -1.021849     1.019004     -1.397064    -1.183812
125      1.643844     0.328414      1.274295     0.790671
99      -0.173674    -0.592373      0.194384     0.132510
33      -0.416010     2.630382     -1.340227    -1.315444
19      -0.900681     1.709595     -1.283389    -1.183812
73       0.310998    -0.592373      0.535409     0.000878
146      0.553333    -1.282963      0.705921     0.922303

In [71]:
xtrain

sepal_length  sepal_width  petal_length  petal_width
91       0.310998    -0.131979      0.478571     0.264142
135      2.249683    -0.131979      1.331133     1.448832
69      -0.294842    -1.282963      0.080709    -0.130755
128      0.674501    -0.592373      1.046945     1.185567
114     -0.052506    -0.592373      0.762758     1.580464
..            ...          ...           ...          ...
133      0.553333    -0.592373      0.762758     0.395774
137      0.674501     0.098217      0.990108     0.790671
72       0.553333    -1.282963      0.649083     0.395774
140      1.038005     0.098217      1.046945     1.580464
37      -1.143017     1.249201     -1.340227    -1.447076

[120 rows x 4 columns]

In [72]:
ytest

14     0
98     1
75     1
16     0
131    2
56     1
141    2
44     0
29     0
120    2
94     1
5      0
102    2
51     1
78     1
42     0
92     1
66     1
31     0
35     0
90     1
84     1
77     1
40     0
125    2
99     1
33     0
19     0
73     1
146    2
Name: species, dtype: int32

In [73]:
ytrain

91     1
135    2
69     1
128    2
114    2
      ..
133    2
137    2
72     1
140    2
37     0
Name: species, Length: 120, dtype: int32

In [17]:
len(xtrain)

120

In [18]:
len(xtest)

30

In [19]:
len(ytrain)

120

In [20]:
len(ytest)

30

In [22]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['species'] = le.fit_transform(df['species']) 

# Model Building 

# Decision Tree Classifier 

In [74]:
from sklearn.tree import DecisionTreeClassifier

In [75]:
dt = DecisionTreeClassifier(criterion='entropy')

dt.fit(xtrain,ytrain)
ypred = dt.predict(xtest)
ypred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [76]:
x.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [77]:
dt.feature_importances_

array([0.00848378, 0.02764493, 0.09849491, 0.86537637])

In [78]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [79]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [80]:
print(accuracy_score(ytest,ypred))

0.9666666666666667


In [81]:
confusion_matrix(ytest,ypred)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [82]:
dt.score(xtrain,ytrain)
dt.score(xtest,ytest)

0.9666666666666667

In [83]:
print('Training accuracy: ', dt.score(xtrain,ytrain))
print('Testing Accuracy: ', np.round(dt.score(xtest,ytest),2))

Training accuracy:  1.0
Testing Accuracy:  0.97


# Deployment 

In [ ]:
# Save the model

In [84]:
import joblib

In [85]:
joblib.dump(dt, "model.pkl")

['model.pkl']

In [86]:
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']

In [87]:
joblib.dump(le,"encoder.pkl")

['encoder.pkl']

In [ ]:
# Sample prediction

In [88]:
model= joblib.load("model.pkl")

In [89]:
scaler=joblib.load("scaler.pkl")

In [91]:
encoder=joblib.load("encoder.pkl")

In [92]:
Input={ 'sepal_length':[5.1], 
       'sepal_width':[3.5], 
       'petal_length':[1.4], 
       'petal_width':[0.2]
    
}

Input=pd.DataFrame(Input)

In [93]:
Input

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [94]:
# Standardlization 
data=scaler.transform(Input)

In [95]:
Input = pd.DataFrame(data, columns=Input.columns)

In [96]:
Input

sepal_length  sepal_width  petal_length  petal_width
0     -0.900681     1.019004     -1.340227    -1.315444

In [103]:
# Make prediction
prediction= model.predict(Input)

In [104]:
prediction

array([0])

In [105]:
prediction = encoder.inverse_transform(prediction)

In [106]:
prediction

array(['setosa'], dtype=object)

In [107]:
prediction[0]

'setosa'